# Generated by Django 4.2 on 2023-06-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=150)),
                ('isFind', models.BooleanField(default=True)),
                ('vk', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(related_name='groups', to='auth.group')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
