# Generated by Django 4.2 on 2023-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamComment',
        ),
    ]
