# Generated by Django 4.2 on 2023-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_additionalinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
