# Generated by Django 4.2 on 2023-06-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_additionalinfo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='login',
            new_name='name',
        ),
    ]
