# Generated by Django 4.2 on 2023-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_login_additionalinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='a',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
