# Generated by Django 4.2 on 2023-06-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_additionalinfo_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='a',
        ),
    ]
