# Generated by Django 4.2 on 2023-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_additionalinfo_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
