# Generated by Django 4.2 on 2023-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_additionalinfo_image_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='groups',
            field=models.ManyToManyField(related_name='info_groups', to='auth.group'),
        ),
    ]
